
#Items type
{120}{}{Armor}
{121}{}{Weapon}
{122}{}{Ammo}
{123}{}{Misc}
{124}{}{Meds}
{125}{}{Explosive}

{126}{}{Return}
{127}{}{Exit}
{128}{}{Next Page}
{129}{}{Previous Page}
#Misc
{100}{}{ (min skill of)}

{130}{}{ - }
{131}{}{Leather Scraps}
{132}{}{Metal Scaps}
{133}{}{Electronics}
{134}{}{Explosive Material}
{135}{}{Weapon Parts}
{136}{}{Medical Supplies}

{140}{}{Repair}
{141}{}{Outdoorsman}
{142}{}{Science}

{149}{}{This functionality is currently unavaible.}
{150}{}{You don't know or don't have enough skill to craft that item.}
# Node 1
{153}{}{This is Pip's Boy 2000 Crafting Terminal. Please pick an option.}
{154}{}{Dismantle an item.}
{155}{}{Upgrade an item.}
{156}{}{Craft items.}
{157}{}{Cheats}

# Node 2 - dismantling
{163}{}{Pick item type for dismantling.}

# Node 5 - dismantling item
{170}{}{Pick item from your inventory to dismatle.}

# Node 6 - crafting
{173}{}{Pick item type you want to craft.}

# Node 7 - crafting item
{177}{}{Pick item you want to craft.}

# Node 3 - upgrading
{179}{}{Pick item type you want to upgrade.}

# Node  - upgrading items
{180}{}{Pick item from your inventory to upgrade.}

# Cheat mode
{199}{}{This is cheat menu - for testing and debug.}
{200}{}{Add 1000 Leather Scraps}
{201}{}{Add 1000 Metal Scraps}
{202}{}{Add 1000 Scrap Electronics}
{203}{}{Add 1000 Explosive Materials}
{204}{}{Add 1000 Weapon Parts}
{205}{}{Add 1000 Medical Supplies}
{206}{}{Get Fallout 2 cheat book}


# Armors 1201-1214 Misc 1216-1225 Ammo 1227-1250 Explosives 1552-1558
{1200}{}{empty}
{1201}{}{Leather Jacket}
{1202}{}{Combat Leather Jacket}
{1203}{}{Leather Armor}
{1204}{}{Leather Armor Mark II}
{1205}{}{Metal Armor}
{1206}{}{Metal Armor Mark II}
{1207}{}{Tesla Armor}
{1208}{}{Combat Armor}
{1209}{}{Combat Armor Mark II}
{1210}{}{Brotherhood Armor}
{1211}{}{Power Armor}
{1212}{}{Hardened Power Armor}
{1213}{}{Advanced Power Armor}
{1214}{}{Adv. Power Armor MKII}
{1215}{}{empty}
{1216}{}{Gecko Pelt}
{1217}{}{Golden Gecko Pelt}
{1218}{}{Fire Gecko Pelt}
{1219}{}{Junk}
{1220}{}{Radio}
{1221}{}{Lighter}
{1222}{}{Water Flask}
{1223}{}{Stealth Boy}
{1224}{}{Geiger Counter}
{1225}{}{Motion Sensor}
{1226}{}{empty}
{1227}{}{Explosive Rocket}
{1228}{}{10mm JHP}
{1229}{}{10mm AP}
{1230}{}{.44 magnum JHP}
{1231}{}{.44 magnum FMJ}
{1232}{}{Flamethrower Fuel}
{1233}{}{Flamethrower Fuel Mk II}
{1234}{}{14mm AP}
{1235}{}{.223mm FMJ}
{1236}{}{5mm JHP}
{1237}{}{5mm AP}
{1238}{}{Rocket AP}
{1239}{}{Small Energy Cell}
{1240}{}{Microfusion Cell}
{1241}{}{12 ga. Shotgun Shell}
{1242}{}{9mm Ball}
{1243}{}{BB's}
{1244}{}{.45 Caliber}
{1245}{}{2mm EC}
{1246}{}{4.7mm Caseless}
{1247}{}{9mm}
{1248}{}{HN Needler Cartrige}
{1249}{}{HN AP Needler Cartrige}
{1250}{}{7.62mm}
{1251}{}{empty}
{1252}{}{Grenade (Frag)}
{1253}{}{Grenade (Plasma)}
{1254}{}{Grenade (Pulse)}
{1255}{}{Holy Hand Grenade}
{1256}{}{Dynamite}
{1257}{}{Plastic Explosives}
{1258}{}{empty}
{1259}{}{First Aid Kit}
{1260}{}{Field Medic First Aid Kit}
{1261}{}{Doctors Bag}
{1262}{}{Paramedics Bag}
{1263}{}{Stimpak}
{1264}{}{Radaway}
{1265}{}{Antidote}
{1266}{}{Mentats}
{1267}{}{Buffout}
{1268}{}{Rad-X}
{1269}{}{Psycho}
{1270}{}{Super Stimpak}
{1271}{}{Jet}
{1272}{}{Jet Antidote}
{1273}{}{Healing Powder}
{1274}{}{empty}
{1275}{}{Knife}
{1276}{}{Club}
{1277}{}{Sledgehammer}
{1278}{}{Crowbar}
{1279}{}{Brass Nuckles}
{1280}{}{Throwing Knife}
{1281}{}{Super Sledge}
{1282}{}{Ripper}
{1283}{}{Cattle prod}
{1284}{}{Spiked nuckles}
{1285}{}{Power Fist}
{1286}{}{Combat Knife}
{1287}{}{Switchblade}
{1288}{}{Shiv}
{1289}{}{Wrench}
{1290}{}{Super Cattle Prod}
{1291}{}{Mega Power Fist}
{1292}{}{Wakisashi Blade}
{1293}{}{"Little Jesus"}
{1294}{}{10mm Pistol}
{1295}{}{10mm SMG}
{1296}{}{Hunting Rifle}
{1297}{}{Desert Eagle .44}
{1298}{}{14mm Pistol}
{1299}{}{Assault Rifle}
{1300}{}{Shotgun}
{1301}{}{9mm Mauser}
{1302}{}{Sniper Rifle}
{1303}{}{Red Ryder BB Gun}
{1304}{}{Red Ryder LE BB Gun}
{1305}{}{.223 Pistol}
{1306}{}{Combat Shotgun}
{1307}{}{Johnny's BB Gun}
{1308}{}{H&K CAWS}
{1309}{}{Tommy Gun}
{1310}{}{Scoped Hunting Rifle}
{1311}{}{H&K P90c}
{1312}{}{Pipe Rifle}
{1313}{}{Zip Gun}
{1314}{}{.44 Magnum Revolver}
{1315}{}{M3A1 "Grease Gun" SMG}
{1316}{}{FN FAL}
{1317}{}{H&K G11}
{1318}{}{XL70E3}
{1319}{}{Pancor Jackhammer}
{1320}{}{Sawed-Off Shotgun}
{1321}{}{Needler Pistol}
{1322}{}{H&K G11E}
{1323}{}{M72 Gauss Rifle}
{1324}{}{PPK12 Gauss Pistol}
{1325}{}{.44 Magnum (Speed Load)}
{1326}{}{FN FAL (Night Sight)}
{1327}{}{Desert Eagle (Exp. Mag.)}
{1328}{}{Assault Rifle (Exp. Mag.)}
{1329}{}{FN FAL HPFA}
{1330}{}{Flamer}
{1331}{}{Minigun}
{1332}{}{Rocket Launcher}
{1333}{}{Bozar}
{1334}{}{Light Support Weapon}
{1335}{}{M60}
{1336}{}{Avenger Minigun}
{1337}{}{Vindicator Minigun}
{1338}{}{Improved Flamer}
{1339}{}{Plasma Rifle}
{1340}{}{Laser Pistol}
{1341}{}{Plasma Pistol}
{1342}{}{Gatling Laser}
{1343}{}{Laser Rifle}
{1344}{}{Turbo Plasma Rifle}
{1345}{}{Laser Rifle (Ext. Cap.)}
{1346}{}{Magneto-Laser Pistol}
{1347}{}{Plasma Pistol (Ext. Cap.)}
{1348}{}{YK32 Pulse Pistol}
{1349}{}{YK42B Pulse Rifle}
{1350}{}{empty}

